services:
  training:
    build:
      context: .
      dockerfile: src/training/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: bash src/pipelines/pipeline_training.sh
    env_file:
      - .env

  predict:
    build:
      context: .
      dockerfile: src/prediction/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    command: python -m src.data.collect_inference --city ${CITY:-Sydney} && python -m src.models.predict --city ${CITY:-Sydney}
    env_file:
      - .env

  api:
    build:
      context: .
      dockerfile: src/api/Dockerfile
    volumes:
      - .:/app
    working_dir: /app

  nginx:
    build:
      context: .
      dockerfile: src/api/Dockerfile.nginx
    ports:
      - "8000:80"
    environment:
      - API_KEY
    depends_on:
      - api

  interface:
    build:
      context: .
      dockerfile: src/interface/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    working_dir: /app
    env_file:
      - .env
  
